apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
spec:
  to: { kind: Service, name: {{ .Values.name }} }
  port: { targetPort: http }
  tls: { termination: edge }
{{- if .Values.route.host }}
  host: {{ .Values.route.host }}
{{- end }}